# Explore Lyrics Data

In [9]:
from pathlib import Path
import pandas as pd

from lana_nlp.preprocessing.data_loader import LyricsDataLoader

In [11]:
df = pd.read_csv("../data/processed/lyrics.csv")

In [12]:
df.head()

,Unnamed: 0,artist,album,song,year,lyrics,basic_cleaned_lyrics,nlp_cleaned_lyrics,word_count,unique_words,...,emotion_Anger,emotion_Anticipation,emotion_Disgust,emotion_Fear,emotion_Joy,emotion_Sadness,emotion_Surprise,emotion_Trust,positive_word_ratio,negative_word_ratio
0,0,Lana Del Rey,Sirens,Drive By,2006,There was a drive-by Sunday night\nMost of us ...,there was a driveby sunday night\nmost of us w...,"['driveby', 'sunday', 'night', 'u', 'bed', 'ri...",251,95,...,0.111111,0.111111,0.030303,0.151515,0.030303,0.181818,0.060606,0.030303,0.028846,0.250000
1,1,Lana Del Rey,Sirens,River Road,2006,"Another day is over, another day is done\nAnd ...",another day is over another day is done\nand n...,"['another', 'day', 'another', 'day', 'done', '...",172,65,...,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.133333,0.200000,0.032967,0.010989
2,2,Lana Del Rey,Sirens,A Star for Nick,2006,"Well, you know it and I know it, I'm gonna be ...",well you know it and i know it I am gonna be a...,"['well', 'know', 'know', 'I', 'gon', 'star', '...",92,45,...,0.000000,0.307692,0.000000,0.000000,0.230769,0.000000,0.000000,0.230769,0.088235,0.000000
3,3,Lana Del Rey,Sirens,My Momma,2006,My momma wouldn't say you were a nice guy\nBut...,my momma would not say you were a nice guy\nbu...,"['momma', 'would', 'say', 'nice', 'guy', '40',...",303,112,...,0.092593,0.092593,0.055556,0.037037,0.111111,0.092593,0.055556,0.074074,0.081081,0.108108
4,4,Lana Del Rey,Sirens,Bad Disease,2006,"Well, there's somethin' about watchin' a crime...",well theres somethin about watchin a crime\nth...,"['well', 'there', 'somethin', 'watchin', 'crim...",238,107,...,0.180451,0.022556,0.150376,0.172932,0.015038,0.187970,0.007519,0.015038,0.045045,0.252252

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            154 non-null    int64
 1   artist                154 non-null    str
 2   album                 154 non-null    str
 3   song                  154 non-null    str
 4   year                  154 non-null    int64
 5   lyrics                153 non-null    str
 6   basic_cleaned_lyrics  153 non-null    str
 7   nlp_cleaned_lyrics    154 non-null    str
 8   word_count            154 non-null    int64
 9   unique_words          154 non-null    int64
 10  syllable_count        154 non-null    int64
 11  line_count            154 non-null    int64
 12  reading_minutes       154 non-null    float64
 13  vocabulary_size       154 non-null    int64
 14  lexical_diversity     154 non-null    float64
 15  average_word_length   154 non-null    float64
 16  flesch_reading_ease   154 non-null    float64
 17  flesch_kincaid        154 non-null    float64
 18  gunning_fog           154 non-null    float64
 19  sentiment_polarity    154 non-null    float64
 20  subjectivity          154 non-null    float64
 21  emotion_Positive      153 non-null    float64
 22  emotion_Negative      153 non-null    float64
 23  emotion_Anger         153 non-null    float64
 24  emotion_Anticipation  153 non-null    float64
 25  emotion_Disgust       153 non-null    float64
 26  emotion_Fear          153 non-null    float64
 27  emotion_Joy           153 non-null    float64
 28  emotion_Sadness       153 non-null    float64
 29  emotion_Surprise      153 non-null    float64
 30  emotion_Trust         153 non-null    float64
 31  positive_word_ratio   154 non-null    float64
 32  negative_word_ratio   154 non-null    float64
dtypes: float64(20), int64(7), str(6)
memory usage: 39.8 KB

In [14]:
df.describe(include="all")

,Unnamed: 0,artist,album,song,year,lyrics,basic_cleaned_lyrics,nlp_cleaned_lyrics,word_count,unique_words,...,emotion_Anger,emotion_Anticipation,emotion_Disgust,emotion_Fear,emotion_Joy,emotion_Sadness,emotion_Surprise,emotion_Trust,positive_word_ratio,negative_word_ratio
count,154.000000,154,154,154,154.000000,153,153,154,154.000000,154.000000,...,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,154.000000,154.000000
unique,NaN,1,11,153,NaN,153,153,154,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Lana Del Rey,Ultraviolence,Yayo,NaN,There was a drive-by Sunday night\nMost of us ...,there was a driveby sunday night\nmost of us w...,"['driveby', 'sunday', 'night', 'u', 'bed', 'ri...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,154,16,2,NaN,1,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,76.500000,NaN,NaN,NaN,2015.441558,NaN,NaN,NaN,318.525974,106.389610,...,0.054617,0.110463,0.036404,0.061819,0.168023,0.084126,0.053934,0.098288,0.135062,0.074191
std,44.600075,NaN,NaN,NaN,5.075878,NaN,NaN,NaN,116.833393,36.115159,...,0.044963,0.066476,0.037241,0.046556,0.073725,0.062589,0.040776,0.059732,0.073233,0.054574
min,0.000000,NaN,NaN,NaN,2006.000000,NaN,NaN,NaN,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.015038,0.000000,0.000000,0.000000,0.000000,0.000000
25%,38.250000,NaN,NaN,NaN,2012.000000,NaN,NaN,NaN,241.000000,86.250000,...,0.019231,0.075000,0.003597,0.025157,0.116438,0.038961,0.025806,0.053030,0.083965,0.034115
50%,76.500000,NaN,NaN,NaN,2015.000000,NaN,NaN,NaN,310.500000,102.000000,...,0.044444,0.095238,0.024691,0.059259,0.165138,0.071895,0.044643,0.093023,0.119109,0.059115
75%,114.750000,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,393.000000,120.000000,...,0.083333,0.138462,0.057143,0.090909,0.201835,0.120000,0.075758,0.129310,0.181647,0.104533
max,153.000000,NaN,NaN,NaN,2023.000000,NaN,NaN,NaN,784.000000,243.000000,...,0.207317,0.409091,0.165468,0.207317,0.500000,0.367347,0.250000,0.283019,0.452381,0.252252

In [15]:
len(df)

154

In [16]:
df["album"].value_counts()

album
Ultraviolence                                          16
Lust for Life                                          16
Did You Know That There's a Tunnel Under Ocean Blvd    16
Sirens                                                 15
Born To Die                                            15
Blue Banisters                                         15
Honeymoon                                              14
Norman Fucking Rockwell!                               14
Lana Del Ray, A.K.A. Lizzy Grant                       13
Chemtrails Over the Country Club                       11
Paradise                                                9
Name: count, dtype: int64

In [17]:
df["year"].value_counts().sort_index()

year
2006    15
2010    13
2012    24
2014    16
2015    14
2016    16
2019    14
2021    26
2023    16
Name: count, dtype: int64

In [18]:
df.isna().sum()

Unnamed: 0              0
artist                  0
album                   0
song                    0
year                    0
lyrics                  1
basic_cleaned_lyrics    1
nlp_cleaned_lyrics      0
word_count              0
unique_words            0
syllable_count          0
line_count              0
reading_minutes         0
vocabulary_size         0
lexical_diversity       0
average_word_length     0
flesch_reading_ease     0
flesch_kincaid          0
gunning_fog             0
sentiment_polarity      0
subjectivity            0
emotion_Positive        1
emotion_Negative        1
emotion_Anger           1
emotion_Anticipation    1
emotion_Disgust         1
emotion_Fear            1
emotion_Joy             1
emotion_Sadness         1
emotion_Surprise        1
emotion_Trust           1
positive_word_ratio     0
negative_word_ratio     0
dtype: int64

In [19]:
df["lyrics"].str.len().describe()

count     153.000000
mean     1571.816993
std       574.000441
min       388.000000
25%      1162.000000
50%      1498.000000
75%      1919.000000
max      3800.000000
Name: lyrics, dtype: float64