# Explore Lyrics Data

In [ ]:
from pathlib import Path

from lana_nlp.scripts.data_loader import LyricsDataLoader

In [ ]:
loader = LyricsDataLoader(
    Path("../data/raw/lyrics.csv")
)

df = loader.load()

In [3]:
df.head()

,artist,album,song,year,lyrics
0,Lana Del Rey,Sirens,Drive By,2006,There was a drive-by Sunday night\nMost of us ...
1,Lana Del Rey,Sirens,River Road,2006,"Another day is over, another day is done\nAnd ..."
2,Lana Del Rey,Sirens,A Star for Nick,2006,"Well, you know it and I know it, I'm gonna be ..."
3,Lana Del Rey,Sirens,My Momma,2006,My momma wouldn't say you were a nice guy\nBut...
4,Lana Del Rey,Sirens,Bad Disease,2006,"Well, there's somethin' about watchin' a crime..."

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  154 non-null    str
 1   album   154 non-null    str
 2   song    154 non-null    str
 3   year    154 non-null    int64
 4   lyrics  153 non-null    str
dtypes: int64(1), str(4)
memory usage: 6.1 KB

In [5]:
df.describe(include="all")

,artist,album,song,year,lyrics
count,154,154,154,154.000000,153
unique,1,11,153,NaN,153
top,Lana Del Rey,Ultraviolence,Yayo,NaN,There was a drive-by Sunday night\nMost of us ...
freq,154,16,2,NaN,1
mean,NaN,NaN,NaN,2015.441558,NaN
std,NaN,NaN,NaN,5.075878,NaN
min,NaN,NaN,NaN,2006.000000,NaN
25%,NaN,NaN,NaN,2012.000000,NaN
50%,NaN,NaN,NaN,2015.000000,NaN
75%,NaN,NaN,NaN,2021.000000,NaN
max,NaN,NaN,NaN,2023.000000,NaN

In [6]:
len(df)

154

In [7]:
df["album"].value_counts()

album
Ultraviolence                                          16
Lust for Life                                          16
Did You Know That There's a Tunnel Under Ocean Blvd    16
Sirens                                                 15
Born To Die                                            15
Blue Banisters                                         15
Honeymoon                                              14
Norman Fucking Rockwell!                               14
Lana Del Ray, A.K.A. Lizzy Grant                       13
Chemtrails Over the Country Club                       11
Paradise                                                9
Name: count, dtype: int64

In [8]:
df["year"].value_counts().sort_index()

year
2006    15
2010    13
2012    24
2014    16
2015    14
2016    16
2019    14
2021    26
2023    16
Name: count, dtype: int64

In [9]:
df.isna().sum()

artist    0
album     0
song      0
year      0
lyrics    1
dtype: int64

In [10]:
df["lyrics"].str.len().describe()

count     153.000000
mean     1571.816993
std       574.000441
min       388.000000
25%      1162.000000
50%      1498.000000
75%      1919.000000
max      3800.000000
Name: lyrics, dtype: float64